version: '3.1'

services:

  mysql-database:
    container_name: mysql-database
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "8083:3306"
    restart: on-failure
    environment:
      # this is not recomended
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: sigadica

  # Este serviço apenas executa a configuração do banco: Criação de tabelas e views
  database-configuration:
    container_name: database-starter
    build:
      context: ./database/
      dockerfile: Dockerfile
    depends_on:
      - mysql-database
    environment:
      MYSQL_DB_USER: root
      MYSQL_DB_PASSWORD: 1234
      MYSQL_DB_HOST: mysql-database
      MYSQL_DB_PORT: 3306
      MYSQL_DB_NAME: sigadica

  # Servico de crud da plataforma SIGADica
  crud-api:
    container_name: crud-api
    build:
      context: ./crud_api/
      dockerfile: Dockerfile
    depends_on:
      - mysql-database
    environment:
      MYSQL_DB_USER: root
      MYSQL_DB_PASSWORD: 1234
      MYSQL_DB_HOST: mysql-database
      MYSQL_DB_PORT: 3306
      MYSQL_DB_NAME: sigadica
      CONTEXT: CONTAINER
    ports:
      - "80:80"

  scraper:
    container_name: scraper-executor
    build:
      context: ./scrapers/
      dockerfile: Dockerfile
    links:
      - "crud-api:scraper"
    depends_on:
      - crud-api
    environment:
      API_HOST: "http://crud-api/"
      MYSQL_DB_USER: root
      MYSQL_DB_PASSWORD: 1234
      MYSQL_DB_HOST: mysql-database
      MYSQL_DB_PORT: 3306
      MYSQL_DB_NAME: sigadica
      CONTEXT: CONTAINER
    ports:
      - "8001:5432"